### ISSUE TITLE
missing type for parse-git-diff on ESM ts file

### ISSUE THREAD

**Issue by onemen** [yeonjuan/parse-git-diff#15]
When using `import parseGitDiff from 'parse-git-diff'` on  .ts file in ESM project with `"type": "module"`,

I get this error for `parseGitDiff `:

```
This expression is not callable.
  Type 'typeof import("c:/_____/node_modules/parse-git-diff/build/index")' has no call signatures.ts(2349)
```

**Comment by yeonjuan** [comment]
@onemen Thank you for your report. We'll take a look and fix it.

**Comment by onemen** [comment]
Thank you 👍👍👍
