### ISSUE TITLE
Issue: Types not found.

### ISSUE THREAD

**Issue by terkelg** [yeonjuan/parse-git-diff#25]
When importing the library in TypeScript, the type declaration isn't found.
I think this issue is caused by `package.json`[ not linking to the correct file.](https://github.com/yeonjuan/parse-git-diff/blob/main/package.json#L7) It's pointing to a types file in the root of the build folder, but the NPM modules doesn't come bundled with that file.

It's also worth noting that the types for ESM and CJS are identical. You can remove the types from the `export` fields and point to a shared types file in `types`. VSCode cannot read the types inside `export` anyway.

![CleanShot 2023-09-30 at 21 58 05@2x](https://github.com/yeonjuan/parse-git-diff/assets/2302254/12890736-f3ab-4538-b267-e62fa806be5d)

**Comment by yeonjuan** [comment]
@terkelg  Thanks for the report! The fixed version `0.0.14` published!
